security:
    encoders:
        App\Entity\User:
            algorithm: auto

    firewalls:
        main:
            anonymous: true
            form_login:
                login_path: login
                check_path: login
            logout:
                path: logout
                target: /

    access_control:
        - { path: ^/admin, roles: ROLE_ADMIN }
        - { path: ^/profile, roles: ROLE_USER }
        - { path: ^/banned, roles: ROLE_BANNED }
